services:
  gridmet-normals:
    platform: linux/amd64
    build: .
    container_name: gridmet-normals
    volumes:
      # Mount data directory to persist downloads and outputs
      - ./data:/app/data
    environment:
      # Set timezone if needed
      - TZ=America/Denver
    restart: "no"
    shm_size: "1g"
    ipc: "host"
    mem_limit: 8g
